apiVersion: v1
kind: Service
metadata:
  name: k3s-dashboard-frontend
  namespace: default
  labels:
    app: k3s-dashboard
    component: frontend
spec:
  type: NodePort
  selector:
    app: k3s-dashboard
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
